export default [
    {
        backgroundColor: "transparent",
        borderColor: "rgba(188,1,38,1)",
        pointBackgroundColor: "rgb(219,174,9)",
        pointRadius: 7,
        pointHoverRadius: 15,
        tension: 0.1,
    },
    {
        backgroundColor: "transparent",
        borderColor: "rgba(1, 116, 188, 1)",
        pointBackgroundColor: "rgb(58,236,13)",
        pointRadius: 7,
        pointHoverRadius: 15,
        tension: 0.1,
    },
    {
        backgroundColor: "transparent",
        borderColor: "rgb(49,98,231)",
        pointBackgroundColor: "rgb(219,9,9)",
        pointRadius: 7,
        pointHoverRadius: 15,
        tension: 0.1,
    },
    {
        backgroundColor: "transparent",
        borderColor: "rgb(20,188,1)",
        pointBackgroundColor: "rgb(54,88,226)",
        pointRadius: 7,
        pointHoverRadius: 15,
        tension: 0.1,
    },
    {
        backgroundColor: "transparent",
        borderColor: "rgb(121,6,234)",
        pointBackgroundColor: "rgb(246,153,57)",
        pointRadius: 7,
        pointHoverRadius: 15,
        tension: 0.1,
    },
    {
        backgroundColor: "transparent",
        borderColor: "rgb(241,138,69)",
        pointBackgroundColor: "rgb(72,106,210)",
        pointRadius: 7,
        pointHoverRadius: 15,
        tension: 0.1,
    },
]
